[package]
name = "runtime-gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
quantos-auth = { version = "0.1.0", path = "../../crates/quantos-auth" }
quantos-core = { version = "0.1.0", path = "../../crates/quantos-core" }
quantos-observability = { version = "0.1.0", path = "../../crates/quantos-observability" }
quantos-policy = { version = "0.1.0", path = "../../crates/quantos-policy" }
quantos-runtime = { version = "0.1.0", path = "../../crates/quantos-runtime" }
quantos-storage = { version = "0.1.0", path = "../../crates/quantos-storage" }
serde_json.workspace = true
tokio.workspace = true
tower-http = { version = "0.6.11", features = ["cors"] }
uuid.workspace = true

[dev-dependencies]
openssl.workspace = true
postgres.workspace = true
postgres-openssl.workspace = true
sha2.workspace = true
url.workspace = true
