[package]
name = "runtime-gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
quantos-auth = { version = "0.1.0", path = "../../crates/quantos-auth" }
quantos-core = { version = "0.1.0", path = "../../crates/quantos-core" }
quantos-observability = { version = "0.1.0", path = "../../crates/quantos-observability" }
quantos-policy = { version = "0.1.0", path = "../../crates/quantos-policy" }
quantos-runtime = { version = "0.1.0", path = "../../crates/quantos-runtime" }
