import type { Meta, StoryObj } from "@storybook/react"; import { useState } from "react"; import { DataGrid, InlineAlert, type DataGridFilter, type DataGridProps, type SortDirection } from "../../index"; import { manyOrders, orderColumns, orders, type OrderFixture } from "../../fixtures/ui103";
function OrderGrid(props: DataGridProps<OrderFixture>) { return <DataGrid {...props} />; }
const base: DataGridProps<OrderFixture> = { title: "订单队列", columns: orderColumns, rows: orders, rowKey: (row) => row.id, page: 1, pageCount: 3, sort: { columnId: "updatedAt", direction: "desc" } };
const meta = { title: "ui/DataGrid", component: OrderGrid, tags: ["autodocs"], args: base } satisfies Meta<typeof OrderGrid>; export default meta; type Story = StoryObj<typeof meta>;
export const Default: Story = {}; export const Loading: Story = { args: { state: "loading", rows: [] } }; export const Empty: Story = { args: { state: "empty", rows: [] } }; export const Error: Story = { args: { state: "error", rows: [], stateMessage: "请重试；若问题持续，请复制关联 ID 联系支持。", correlationId: "cor-error-103" } }; export const Unauthorized: Story = { args: { state: "unauthorized", rows: [], stateMessage: "请联系主工作区管理员。" } }; export const Stale: Story = { args: { state: "stale", rows: [], stateMessage: "刷新数据后才能继续高风险操作。" } }; export const Offline: Story = { args: { state: "offline", rows: [], stateMessage: "只读缓存可用，变更操作已暂停。" } }; export const DangerConfirmNotApplicable: Story = { render: () => <InlineAlert title="不适用">DataGrid 本身不执行危险动作；危险确认由 DangerConfirmDialog 承担。</InlineAlert> };
export const Zoom200: Story = { render: (args) => <div data-testid="zoom-200-surface" style={{ zoom: 2, width: "50%" }}><OrderGrid {...args} /></div>, parameters: { docs: { description: { story: "UI-103 200% 缩放回流基线：画布占用等效半宽，宽表保持组件内滚动。" } } } };
function InteractiveOrderGrid() { const [filters, setFilters] = useState<DataGridFilter[]>([{ id: "symbol", label: "标的", value: "", placeholder: "BTC-USDT" }]); const [visible, setVisible] = useState(orderColumns.map((column) => column.id)); const [sort, setSort] = useState<{ columnId: string; direction: SortDirection }>({ columnId: "updatedAt", direction: "desc" }); return <DataGrid {...base} filters={filters} visibleColumnIds={visible} sort={sort} urlSync={{ enabled: true, namespace: "orders" }} onFilterChange={(id, value) => setFilters((current) => current.map((filter) => filter.id === id ? { ...filter, value } : filter))} onVisibleColumnIdsChange={setVisible} onSortChange={(columnId, direction) => setSort({ columnId, direction })} />; }
export const FilterColumnAndUrlSync: Story = { render: () => <InteractiveOrderGrid /> };
export const VirtualizedThousandRows: Story = { args: { rows: manyOrders, pageCount: 1, virtualize: true, viewportRows: 10 }, parameters: { docs: { description: { story: "1,000 行 fixture 仅渲染可视窗口与 overscan 行；首列固定。" } } } };
