/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前会话与 MFA 状态 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 主工作区/账户上下文与 capability 集合（权限裁剪的唯一来源） */
        get: operations["getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 近期登录再认证（高风险操作前置） */
        post: operations["reauth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起/完成 MFA challenge（失败限流且不泄露账户存在性） */
        post: operations["mfaChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注销并服务端吊销会话 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 访问申请（访客；防滥用限速 + 隐私告知版本） */
        post: operations["submitAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前成员资料与区域显示偏好 */
        get: operations["getProfile"];
        /** 保存资料与区域显示偏好；不得改变角色、权限或风险规则 */
        put: operations["saveProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationPrefs"];
        put: operations["saveNotificationPrefs"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSecuritySettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销单个非当前会话；要求近期认证并写审计 */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/sessions/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeSessionRevocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/trusted-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/trusted-devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销设备信任；不得撤销最后有效 MFA 因素 */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setupMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/mfa/factors/{factorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销 MFA 因素；最后有效因素必须返回 409 且不得修改状态 */
        delete: operations["revokeMfaFactor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDownloads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/browser-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web adapter 服务端约束；客户端本地检测只能缩小能力，不得扩大授权 */
        get: operations["getPlatformCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 研究任务列表（服务端分页/筛选/排序） */
        get: operations["listResearchRuns"];
        put?: never;
        /** 创建研究任务（幂等；capability/快照/预算/deadline 服务端校验） */
        post: operations["createResearchRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情（含 Evidence：快照/Engine/hash/成本/correlationId） */
        get: operations["getResearchRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research-runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 请求取消（202 受理；终态以流/详情为准，不伪造已取消） */
        post: operations["cancelResearchRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research-runs/{runId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务事件流（SSE；sequence 去重，afterSequence 回补） */
        get: operations["subscribeResearchRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDataSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-snapshots/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 快照详情（质量/血缘/许可；质量受限由服务端返回阻断标识，前端不可覆盖） */
        get: operations["getDataSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact 详情（版本/环境 hash/血缘；资源级授权，无权按 404） */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{strategyId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStrategyDraft"];
        /** 保存草稿（If-Match=expectedVersion；409 返回 currentVersion，客户端保留草稿不覆盖） */
        put: operations["saveStrategyDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{strategyId}/static-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 静态检查（look-ahead/依赖/数据快照阻断原因） */
        post: operations["runStaticCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起回测（固定快照与 clock；202 受理） */
        post: operations["createBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleases"];
        put?: never;
        /** 创建不可变 Release（泄漏检查失败阻断；返回 content hash） */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release 详情（allowedTargets 由服务端返回；M3/M4 仅 paper/shadow） */
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{releaseId}/approval-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitReleaseApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{releaseId}/rollback-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestReleaseRollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合视图（asOf/stale；陈旧时命令类操作由服务端拒绝） */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRiskView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk/kill-switch/engage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发 kill switch（DangerConfirm + MFA + reauthTokenRef + 服务端签名） */
        post: operations["engageKillSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk/kill-switch/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解除 kill switch（同 engage 约束） */
        post: operations["releaseKillSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合/风险授权投影流（含 kill switch 广播） */
        get: operations["subscribePortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 建议详情（executable 恒 false；无下单语义） */
        get: operations["getProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposals/{proposalId}/risk-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 请求风险评估（携带 proposal/version/context hash；过期/陈旧/未发布/无权限服务端拒绝） */
        post: operations["requestRiskEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposals/{proposalId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 待办列表（仅审批人可见；禁自批由服务端强制） */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approvalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审批详情（操作前客户端必须重取以刷新版本/有效期） */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approvalId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批准/拒绝/需要更多信息（MFA 签名；并发/过期/额度变化 409 强制刷新） */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交已批准的 command ref（客户端不构造命令体；202 受理，成交以 Order 事件为准） */
        post: operations["submitTradeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/cancel-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤单请求（仅传服务端验证过的 command ref + 幂等键；202 受理） */
        post: operations["requestOrderCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单事件流（sequence 去重；断流回补；ack 前不得显示成交） */
        get: operations["subscribeOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        /**
         * Format: date-time
         * @description RFC 3339 UTC
         */
        DateTime: string;
        /** @description 十进制定点字符串（proto DecimalValue.value；禁 IEEE-754 交易计算） */
        DecimalValue: string;
        MoneyValue: {
            currencyCode: string;
            /** Format: int64 */
            units: string;
            nanos: number;
        };
        /**
         * @description assisted_live 仅 M5+ 且服务端 flag/capability 放行才可见；客户端不得硬编码可用性
         * @enum {string}
         */
        RuntimeMode: "research" | "paper" | "shadow" | "assisted_live";
        /** @enum {string} */
        Environment: "dev" | "staging" | "prod";
        /**
         * @description 未知值客户端显示"未知/需升级"并阻断高风险动作
         * @enum {string}
         */
        DataQuality: "verified" | "provisional" | "degraded" | "failed" | "expired" | "license_missing";
        /** @enum {string} */
        TaskStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "cancel_requested";
        /** @enum {string} */
        OrderStatus: "draft" | "risk_checking" | "awaiting_approval" | "command_ready" | "submitted" | "accepted" | "partially_filled" | "filled" | "cancelled" | "rejected" | "expired";
        TimeWindow: {
            start: components["schemas"]["DateTime"];
            end: components["schemas"]["DateTime"];
        };
        ErrorEnvelope: {
            /** @description 稳定机器码，如 FORBIDDEN/VERSION_CONFLICT/COMMAND_EXPIRED/DATA_STALE */
            code: string;
            /** @description 安全可展示文案（i18n key 由客户端映射） */
            message: string;
            correlationId: components["schemas"]["UUID"];
            fieldErrors?: {
                [key: string]: string;
            };
            /** @description 秒 */
            retryAfter?: number;
            /** @description 409 时返回，供客户端 diff */
            currentVersion?: string;
        };
        Page: {
            items: unknown[];
            /** @description 缺省表示末页 */
            nextCursor?: string;
        };
        AsyncAccepted: {
            jobId: components["schemas"]["UUID"];
            /** @enum {string} */
            status: "accepted" | "cancel_requested";
            correlationId: components["schemas"]["UUID"];
        };
        AuditedAsyncAccepted: components["schemas"]["AsyncAccepted"] & {
            auditRef: components["schemas"]["UUID"];
        };
        ReauthRequest: {
            challengeRef: components["schemas"]["UUID"];
        };
        StreamEvent: {
            streamId: components["schemas"]["UUID"];
            /** Format: int64 */
            sequence: number;
            eventId: components["schemas"]["UUID"];
            occurredAt: components["schemas"]["DateTime"];
            correlationId: components["schemas"]["UUID"];
            /** @description 载荷 schema 版本（未知版本客户端 fail closed） */
            payloadVersion: string;
            /** @description 领域事件载荷；payload.type=permission_revoked 为终态语义 */
            payload: Record<string, never>;
        };
        SessionContext: {
            actorId: components["schemas"]["UUID"];
            tenantId: components["schemas"]["UUID"];
            workspaceId: components["schemas"]["UUID"];
            accountId: components["schemas"]["UUID"];
            mode: components["schemas"]["RuntimeMode"];
            environment: components["schemas"]["Environment"];
            /** @description capability key 全集（权限裁剪唯一来源） */
            capabilities: string[];
            /** @enum {string} */
            mfaState: "unenrolled" | "enrolled" | "challenged" | "verified";
            expiresAt: components["schemas"]["DateTime"];
        };
        ProfileSettingsInput: {
            displayName: string;
            title?: string;
            team?: string;
            /** @enum {string} */
            locale: "zh-CN" | "en";
            /** @description IANA timezone */
            timezone: string;
            /** @enum {string} */
            theme: "system" | "dark" | "light";
            /** @enum {string} */
            numberFormat: "comma_dot" | "space_comma";
            /** @enum {string} */
            timeDisplay: "utc_local" | "local";
            /** @enum {string} */
            defaultRoute: "/command" | "/research" | "/portfolio" | "/markets";
            /** @enum {string} */
            density: "compact" | "comfortable";
            highContrast: boolean;
            reducedMotion: boolean;
        };
        ProfileSettings: components["schemas"]["ProfileSettingsInput"] & {
            memberId: string;
            /** Format: email */
            readonly email: string;
            readonly emailVerified: boolean;
            readonly roleLabels: string[];
            objectVersion: string;
        };
        NotificationRule: {
            key: string;
            /** @enum {string} */
            severity: "critical" | "warning" | "info";
            inApp: boolean;
            desktop: boolean;
            email: boolean;
            browser: boolean;
        };
        NotificationPreferencesInput: {
            rules: components["schemas"]["NotificationRule"][];
            quietHoursEnabled: boolean;
            quietHoursStart: string;
            quietHoursEnd: string;
            /** @description Critical 可绕过静默但仍受服务端授权策略约束 */
            criticalBypass: boolean;
            /** @enum {string} */
            digestFrequency: "off" | "daily" | "weekly";
        };
        NotificationPreferences: components["schemas"]["NotificationPreferencesInput"] & {
            objectVersion: string;
            /** @enum {string} */
            browserPermission: "granted" | "denied" | "default" | "unsupported";
        };
        MfaFactor: {
            factorId: string;
            /** @enum {string} */
            method: "passkey" | "authenticator" | "recovery_codes";
            label: string;
            createdAt: components["schemas"]["DateTime"];
            lastUsedAt: components["schemas"]["DateTime"];
            currentDevice: boolean;
        };
        SecuritySettings: {
            /** @enum {string} */
            posture: "strong" | "attention_required" | "unknown";
            score: number;
            mfaEnabled: boolean;
            factors: components["schemas"]["MfaFactor"][];
            recoveryCodesRemaining: number;
            lastVerifiedAt: components["schemas"]["DateTime"];
            correlationId: components["schemas"]["UUID"];
        };
        ActiveSession: {
            sessionId: string;
            client: string;
            platform: string;
            location: string;
            lastActiveAt: components["schemas"]["DateTime"];
            /** @description 仅脱敏 IP，禁止返回完整地址 */
            ipMasked: string;
            current: boolean;
        };
        TrustedDevice: {
            deviceId: string;
            label: string;
            /** @enum {string} */
            verificationMethod: "passkey" | "biometric" | "authenticator";
            trustedUntil: components["schemas"]["DateTime"];
            current: boolean;
        };
        DownloadRecord: {
            downloadId: string;
            objectLabel: string;
            format: string;
            requestedAt: components["schemas"]["DateTime"];
            /** @enum {string} */
            status: "preparing" | "ready" | "downloaded" | "expired" | "failed";
            expiresAt?: components["schemas"]["DateTime"];
            /**
             * Format: uri
             * @description BFF 短时签名 URL；不得写入日志或持久化
             */
            downloadUrl?: string;
            watermarked?: boolean;
            correlationId?: components["schemas"]["UUID"];
        };
        BrowserCapabilityPolicy: {
            /** @enum {string} */
            kind: "web";
            /** @enum {string} */
            authFlow: "browser_redirect";
            /** @enum {string} */
            notifications: "browser";
            /** @enum {boolean} */
            localFileImport: false;
            /** Format: uri */
            deepLinkScheme: string;
            /** @enum {boolean} */
            downloadsViaBff: true;
            /** @enum {boolean} */
            offlineDomainActions: false;
            /** @enum {boolean} */
            businessPagesNoIndex: true;
            cspEnforced: boolean;
            sessionProtected: boolean;
        };
        ResearchRun: {
            runId: components["schemas"]["UUID"];
            capability: string;
            dataSnapshotId: components["schemas"]["UUID"];
            budget: components["schemas"]["DecimalValue"];
            costUnits?: components["schemas"]["DecimalValue"];
            deadlineAt: components["schemas"]["DateTime"];
            status: components["schemas"]["TaskStatus"];
            inputHash: string;
            engineVersion: string;
            artifactRefs?: components["schemas"]["UUID"][];
            evidenceRefs: components["schemas"]["UUID"][];
            correlationId: components["schemas"]["UUID"];
            createdAt: components["schemas"]["DateTime"];
        };
        DataSnapshot: {
            snapshotId: components["schemas"]["UUID"];
            schemaVersion: string;
            window: components["schemas"]["TimeWindow"];
            sources?: string[];
            quality: components["schemas"]["DataQuality"];
            /** @description 质量受限阻断标识（服务端权威，前端不可覆盖） */
            qualityBlocked?: boolean;
            contentHash: string;
            licenseLabel: string;
            capturedAt: components["schemas"]["DateTime"];
            /** Format: int64 */
            maxAgeSeconds: number;
        };
        Artifact: {
            artifactId: components["schemas"]["UUID"];
            hypothesis: string;
            summary: string;
            engineVersion: string;
            promptVersion: string;
            codeVersion: string;
            environmentHash: string;
            dataSnapshotId: components["schemas"]["UUID"];
            contentHash: string;
            lineageRefs?: components["schemas"]["UUID"][];
            createdAt: components["schemas"]["DateTime"];
        };
        StrategySummary: {
            strategyId: components["schemas"]["UUID"];
            name: string;
            updatedAt: components["schemas"]["DateTime"];
        };
        StrategyDraft: {
            strategyId: components["schemas"]["UUID"];
            objectVersion: string;
            files: {
                [key: string]: string;
            };
            parameters: Record<string, never>;
            updatedAt: components["schemas"]["DateTime"];
        };
        BacktestReport: {
            runId: components["schemas"]["UUID"];
            strategyId: components["schemas"]["UUID"];
            dataSnapshotId: components["schemas"]["UUID"];
            status: components["schemas"]["TaskStatus"];
            metrics: {
                [key: string]: components["schemas"]["DecimalValue"];
            };
            /** @description 泄漏检查失败规则码（非空阻断 Release） */
            leakViolations: string[];
            reportArtifactId: components["schemas"]["UUID"];
        };
        StrategyRelease: {
            releaseId: components["schemas"]["UUID"];
            strategyId: components["schemas"]["UUID"];
            backtestReportArtifactId: components["schemas"]["UUID"];
            sourceDigest: string;
            imageDigest: string;
            parameterHash: string;
            parameters: Record<string, never>;
            snapshotId: components["schemas"]["UUID"];
            /** @description 服务端权威；M3/M4 仅 paper/shadow；assisted_live 出现需 flag 放行 */
            allowedTargets: ("paper" | "shadow" | "assisted_live")[];
            /** @enum {string} */
            approvalState: "none" | "pending" | "approved" | "rejected" | "expired";
            createdAt: components["schemas"]["DateTime"];
        };
        Position: {
            symbol: string;
            /** @enum {string} */
            side: "long" | "short";
            quantity: components["schemas"]["DecimalValue"];
            avgPrice: components["schemas"]["DecimalValue"];
        };
        PortfolioView: {
            accountId: components["schemas"]["UUID"];
            asOf: components["schemas"]["DateTime"];
            /** @description true 时命令类操作由服务端拒绝 */
            stale: boolean;
            positions: components["schemas"]["Position"][];
            pnl: components["schemas"]["MoneyValue"];
            exposure: components["schemas"]["DecimalValue"];
        };
        RiskView: {
            accountId: components["schemas"]["UUID"];
            asOf: components["schemas"]["DateTime"];
            hitRules: string[];
            limitIds: components["schemas"]["UUID"][];
            killSwitch: {
                /** @enum {string} */
                state: "disengaged" | "engaged";
                actor?: string;
                at?: components["schemas"]["DateTime"];
            };
        };
        Signal: {
            signalId: components["schemas"]["UUID"];
            strategyReleaseId: components["schemas"]["UUID"];
            symbol: string;
            /** @enum {string} */
            direction: "long" | "short" | "flat";
            strength: components["schemas"]["DecimalValue"];
            confidence: components["schemas"]["DecimalValue"];
            generatedAt: components["schemas"]["DateTime"];
            validUntil: components["schemas"]["DateTime"];
        };
        TradeProposal: {
            proposalId: components["schemas"]["UUID"];
            accountId: components["schemas"]["UUID"];
            symbol: string;
            /** @enum {string} */
            action: "buy" | "sell" | "reduce" | "close";
            quantity: components["schemas"]["DecimalValue"];
            notional: components["schemas"]["DecimalValue"];
            signal: components["schemas"]["Signal"];
            rationale: string;
            /** @description 反方观点（R04 强制；proto trading.v1.TradeProposal.counter_views） */
            counterViews: string[];
            evidenceRefs: components["schemas"]["UUID"][];
            confidence: components["schemas"]["DecimalValue"];
            expiresAt: components["schemas"]["DateTime"];
            /**
             * @description 恒 false（A02；schema 层强制）
             * @enum {boolean}
             */
            executable: false;
            objectVersion: string;
        };
        Approval: {
            approvalId: components["schemas"]["UUID"];
            /** @description 发起人 actorId（禁自批判定） */
            originator: string;
            objectVersion: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "expired" | "conflict";
            expiresAt: components["schemas"]["DateTime"];
            /** @description 批准后服务端签名 */
            signature?: string;
            /** @description 批准后签发的短时 TradeCommand 引用 */
            commandRef?: components["schemas"]["UUID"];
            correlationId: components["schemas"]["UUID"];
        };
        Fill: {
            fillId: components["schemas"]["UUID"];
            quantity: components["schemas"]["DecimalValue"];
            price: components["schemas"]["DecimalValue"];
            at: components["schemas"]["DateTime"];
        };
        Order: {
            orderId: components["schemas"]["UUID"];
            commandId: components["schemas"]["UUID"];
            decisionId?: components["schemas"]["UUID"];
            proposalId?: components["schemas"]["UUID"];
            releaseId?: components["schemas"]["UUID"];
            accountId: components["schemas"]["UUID"];
            venue: string;
            /** @enum {string} */
            venueKind: "binance" | "okx" | "coinbase" | "ibkr" | "alpine" | "mock";
            symbol: string;
            /** @enum {string} */
            intent: "open" | "increase" | "reduce" | "close";
            /** @enum {string} */
            side: "buy" | "sell";
            quantity: components["schemas"]["DecimalValue"];
            prices?: components["schemas"]["DecimalValue"][];
            status: components["schemas"]["OrderStatus"];
            filledQuantity: components["schemas"]["DecimalValue"];
            averageFillPrice: components["schemas"]["DecimalValue"];
            fills: components["schemas"]["Fill"][];
            mode: components["schemas"]["RuntimeMode"];
            correlationId: components["schemas"]["UUID"];
            submittedAt: components["schemas"]["DateTime"];
        };
    };
    responses: {
        /** @description 会话失效/未认证；客户端清空内存态并跳登录（不泄露细节） */
        Unauthorized: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHENTICATED",
                 *       "message": "会话已失效，请重新登录。",
                 *       "correlationId": "9a1c4e60-2d3b-4c5f-8a9e-1b2c3d4e5f60"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 无权限（规范文案；涉密钥/受限审计/高风险不返回内容） */
        Forbidden: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "你没有访问此资源的权限。若认为这是错误，请联系主工作区管理员。",
                 *       "correlationId": "4d5e6f70-8a9b-4c1d-2e3f-5a6b7c8d9e0f"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 不存在或未授权（不区分，防存在性泄露） */
        NotFound: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "未找到该资源。",
                 *       "correlationId": "4d5e6f70-8a9b-4c1d-2e3f-5a6b7c8d9e0f"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 版本/状态/有效期冲突；返回 currentVersion，客户端保留本地草稿并刷新 */
        Conflict: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 校验失败（字段级 fieldErrors；含超预算/过期数据/未批准 capability 等原因） */
        Unprocessable: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 限流（retryAfter 秒；不泄露账户存在性） */
        RateLimited: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description 不透明分页游标 */
        Cursor: string;
        PageSize: number;
        /** @description 服务端排序表达式；允许值由具体 operation 明确列出，未知字段返回 422 */
        Sort: string;
        /** @description 服务端过滤表达式；仅接受具体 operation allowlist 中的字段 */
        Filter: string;
        /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
        IdempotencyKey: string;
        /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
        IfMatch: string;
        /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
        AfterSequence: number;
        /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description 全链路追踪 ID；错误页可复制提交支持 */
        "X-Correlation-Id": string;
        /** @description 当前对象版本；后续可变写使用 If-Match 原样回传 */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话信息 */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上下文 */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    reauth: {
        parameters: {
            query?: never;
            header: {
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthRequest"];
            };
        };
        responses: {
            /** @description 再认证通过，返回新的 reauthTokenRef（短时） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        reauthTokenRef: string;
                        expiresAt: components["schemas"]["DateTime"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    mfaChallenge: {
        parameters: {
            query?: never;
            header: {
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    purpose: "login" | "approval" | "kill_switch" | "security_change";
                    /** @description 完成 challenge 时提交；发起时缺省 */
                    code?: string;
                };
            };
        };
        responses: {
            /** @description challenge 状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        challengeRef: string;
                        /** @enum {string} */
                        status: "pending" | "verified" | "failed";
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已注销 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    teamName: string;
                    /** Format: email */
                    contactEmail: string;
                    purpose: string;
                    markets: string[];
                    expectedMode: components["schemas"]["RuntimeMode"];
                    privacyNoticeVersion: string;
                };
            };
        };
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditedAsyncAccepted"];
                };
            };
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资料设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSettingsInput"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getNotificationPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知偏好矩阵 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
        };
    };
    saveNotificationPrefs: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferencesInput"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getSecuritySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MFA 与安全姿态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecuritySettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 活跃会话（IP 必须脱敏） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSession"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-Reauth-Token-Ref": string;
            };
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 撤销已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditedAsyncAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    subscribeSessionRevocations: {
        parameters: {
            query?: {
                /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话撤销/失效 SSE；当前会话被撤销为终态并清空内存认证态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可信设备 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustedDevice"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-Reauth-Token-Ref": string;
            };
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 撤销已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditedAsyncAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setupMfa: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-Reauth-Token-Ref": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    method: "passkey" | "authenticator";
                };
            };
        };
        responses: {
            /** @description MFA 设置流程已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditedAsyncAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeMfaFactor: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 与 SameSite CSRF cookie 绑定的双提交 token；BFF 同时校验 Origin allowlist */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "X-Reauth-Token-Ref": string;
            };
            path: {
                factorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 因素撤销已受理；auditRef 可追踪安全审计记录 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditedAsyncAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listDownloads: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下载记录；URL 必须短时、签名且服务端鉴权 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["DownloadRecord"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPlatformCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Web 平台能力策略 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserCapabilityPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listResearchRuns: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["TaskStatus"];
                dataSnapshotId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["ResearchRun"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createResearchRun: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    capability: string;
                    /** Format: uuid */
                    dataSnapshotId: string;
                    question: string;
                    budget: components["schemas"]["DecimalValue"];
                    deadlineAt: components["schemas"]["DateTime"];
                    /** @description 已上传扫描后的 Artifact 引用 */
                    attachments?: string[];
                };
            };
        };
        responses: {
            /** @description 受理（不代表完成） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    getResearchRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelResearchRun: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取消已受理（cancel_requested） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    subscribeResearchRun: {
        parameters: {
            query?: {
                /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listDataSnapshots: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                quality?: components["schemas"]["DataQuality"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 快照页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["DataSnapshot"][];
                    };
                };
            };
        };
    };
    getDataSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listStrategies: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 策略页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["StrategySummary"][];
                    };
                };
            };
        };
    };
    getStrategyDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 草稿（携带 objectVersion/ETag） */
            200: {
                headers: {
                    /** @description objectVersion */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDraft"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    saveStrategyDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                strategyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    files: {
                        [key: string]: string;
                    };
                    parameters: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 已保存，返回新 objectVersion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDraft"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    runStaticCheck: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                strategyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
        };
    };
    createBacktest: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    strategyId: string;
                    objectVersion: string;
                    /** Format: uuid */
                    dataSnapshotId: string;
                };
            };
        };
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 回测报告（指标/泄漏检查/验证结果） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReleases: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release 页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["StrategyRelease"][];
                    };
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    strategyId: string;
                    objectVersion: string;
                    /** Format: uuid */
                    backtestRunId: string;
                    parameters: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRelease"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRelease"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    submitReleaseApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已进入审批 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    requestReleaseRollback: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    targetReleaseId: string;
                };
            };
        };
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
        };
    };
    getPortfolio: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 组合视图 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioView"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRiskView: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 风险视图（预算/命中规则/kill switch 状态） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskView"];
                };
            };
        };
    };
    engageKillSwitch: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    accountId: string;
                    reason: string;
                    /** Format: uuid */
                    mfaChallengeRef: string;
                    /** Format: uuid */
                    reauthTokenRef: string;
                    /** @description 客户端 DangerConfirm 输入的确认短语 */
                    confirmPhrase: string;
                };
            };
        };
        responses: {
            /** @description 已触发（含审计 correlationId） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskView"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    releaseKillSwitch: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    accountId: string;
                    reason: string;
                    /** Format: uuid */
                    mfaChallengeRef: string;
                    /** Format: uuid */
                    reauthTokenRef: string;
                };
            };
        };
        responses: {
            /** @description 已解除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskView"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    subscribePortfolio: {
        parameters: {
            query: {
                accountId: string;
                /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listProposals: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                status?: string;
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 建议页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["TradeProposal"][];
                    };
                };
            };
        };
    };
    getProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 建议 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeProposal"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestRiskEvaluation: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description quoteRef/accountRef/mode/版本组合 hash */
                    contextHash: string;
                };
            };
        };
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    subscribeProposal: {
        parameters: {
            query?: {
                /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审批页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Approval"][];
                    };
                };
            };
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审批 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description expectedVersion（objectVersion）；不匹配返回 409 + currentVersion */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "reject" | "request_info";
                    /** @description decision≠approve 时必填，写入审计 */
                    reason?: string;
                    /** Format: uuid */
                    mfaChallengeRef: string;
                    /** Format: uuid */
                    reauthTokenRef?: string;
                };
            };
        };
        responses: {
            /** @description 已记录（批准时含 commandRef，服务端最终校验仍可在提交时拒绝） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    submitTradeCommand: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description 服务端签发的短时 TradeCommand 引用
                     */
                    commandRef: string;
                };
            };
        };
        responses: {
            /** @description 受理（Execution Gateway 二次校验仍可能拒绝） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listOrders: {
        parameters: {
            query: {
                /** @description 不透明分页游标 */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                accountId: string;
                status?: components["schemas"]["OrderStatus"];
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 订单页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Order"][];
                    };
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 订单（状态机/成交/关联 proposal/decision/release） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestOrderCancel: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图重试必须复用同一键；服务端按（actor, key）去重 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    commandRef: string;
                };
            };
        };
        responses: {
            /** @description 受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncAccepted"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    subscribeOrder: {
        parameters: {
            query?: {
                /** @description 只推送 sequence 严格大于该值的事件（断线回补） */
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
