"use client";

import { useEffect, useMemo, useState } from "react";
import { shouldExposeBrowserSettings, type PlatformKind } from "@sumalpha/platform/adapter";
import { Button, DangerConfirmDialog, InlineAlert, ThemeProvider } from "@sumalpha/ui";
import {
  canRevokeDevice, canRevokeSession, detectBrowserRuntime, downloadAvailability, notificationFallback,
  type BrowserPermissionState, type BrowserRuntimeCapabilities, type NotificationPreferences, type ProfileSettings, type SettingsBundle,
} from "../../../src/settings/c17";

export type SettingsSection = "profile" | "notifications" | "security" | "browser";
export type SettingsPageState = "default" | "loading" | "empty" | "error" | "unauthorized" | "stale" | "offline";
export interface SettingsWorkspaceProps { section: SettingsSection; initialData: SettingsBundle; contractMode?: "mocked" | "integrated"; pageState?: SettingsPageState; platformKind?: PlatformKind }

const settingsNavigation: { id: SettingsSection; href: string; label: string; icon: string; webOnly?: boolean }[] = [
  { id: "profile", href: "/settings/profile", label: "个人资料", icon: "♙" }, { id: "notifications", href: "/settings/notifications", label: "通知设置", icon: "♧" },
  { id: "security", href: "/settings/security", label: "安全与 MFA", icon: "♢" }, { id: "browser", href: "/settings/browser", label: "Web Browser", icon: "◎", webOnly: true },
];
const ruleLabels: Record<string, string> = { critical_risk: "Critical risk / Kill switch", approval_expiring: "Approval expiring", order_rejected: "Order rejected / partial fill", incident_assigned: "Incident assigned", research_completed: "Research completed", report_ready: "Report / export ready" };
const channelLabels = { inApp: "In-app", desktop: "Desktop", email: "Email", browser: "Browser" } as const;
type NotificationChannel = keyof typeof channelLabels;

function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Shanghai" }).format(new Date(value)); }
function MiniToggle({ checked, onChange, label, disabled }: { checked: boolean; onChange: (value: boolean) => void; label: string; disabled?: boolean }) { return <label className={`settings-toggle${disabled ? " disabled" : ""}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span aria-hidden="true" /><b>{label}</b></label>; }
function SettingsHeader({ section }: { section: SettingsSection }) { const labels = { profile: ["Profile & Settings", "管理个人资料、显示偏好与区域设置。"], notifications: ["Notification settings", "配置授权渠道、静默时段与关键安全提醒。"], security: ["Security & MFA", "管理 MFA、活跃会话、可信设备与安全操作。"], browser: ["Browser settings", "查看浏览器通知、下载、存储、深链与响应式限制。"] } as const; return <header className="settings-page-header"><div><p className="settings-breadcrumb">Settings <span>/</span> {section}</p><h1>{labels[section][0]}</h1><p>{labels[section][1]}</p></div><div className="settings-header-actions"><Button>查看安全审计</Button><Button>快捷键</Button><Button aria-label="关闭设置">× 关闭</Button></div></header>; }
function SettingsIdentity({ profile, active, platformKind }: { profile: ProfileSettings; active: SettingsSection; platformKind: PlatformKind }) { return <aside className="settings-rail" aria-label="设置导航"><div className="settings-person"><span>{profile.displayName.split(" ").map((part) => part[0]).join("")}</span><strong>{profile.displayName}</strong><small>{profile.email}</small><b>{profile.roleLabels[0]}</b><small>{profile.memberId} · <i>● Active</i></small></div><nav>{settingsNavigation.filter((item) => !item.webOnly || shouldExposeBrowserSettings(platformKind)).map((item) => <a key={item.id} href={item.href} className={active === item.id ? "active" : ""} aria-current={active === item.id ? "page" : undefined}><i aria-hidden="true">{item.icon}</i>{item.label}{item.id === "security" ? <em>3</em> : null}</a>)}</nav><div className="settings-workspace-card"><strong>▣ Primary workspace</strong><span>角色：administrator</span><span>权限：已授权</span></div></aside>; }

function SettingsState({ state }: { state: Exclude<SettingsPageState, "default" | "stale" | "offline"> }) {
  const copy = {
    loading: ["正在加载设置", "正在通过 C17 聚合当前成员设置。"],
    empty: ["暂无可配置设置", "当前角色没有可编辑的设置项。"],
    error: ["设置加载失败", "请重试；若问题持续，请携带 Correlation ID 联系管理员。"],
    unauthorized: ["无权查看此设置", "当前会话或角色未获授权，页面不会展示隐藏领域数据。"],
  } as const;
  return <section className="settings-card settings-state" role={state === "error" ? "alert" : "status"}><span aria-hidden="true">{state === "loading" ? "◌" : state === "empty" ? "◇" : state === "error" ? "△" : "⊘"}</span><h2>{copy[state][0]}</h2><p>{copy[state][1]}</p>{state === "error" ? <Button>重试</Button> : null}</section>;
}

function ProfilePanel({ profile, onChange, onSave }: { profile: ProfileSettings; onChange: (next: ProfileSettings) => void; onSave: () => void }) {
  return <div className="settings-column"><section className="settings-card"><h2>个人资料</h2><div className="settings-form-grid"><label>显示名称<input value={profile.displayName} onChange={(event) => onChange({ ...profile, displayName: event.target.value })} /></label><label>电子邮件<input value={profile.email} readOnly aria-describedby="verified-email" /></label><label>职位<input value={profile.title ?? ""} onChange={(event) => onChange({ ...profile, title: event.target.value })} /></label><label>团队<input value={profile.team ?? ""} onChange={(event) => onChange({ ...profile, team: event.target.value })} /></label></div><p className="settings-note" id="verified-email">ⓘ 电子邮件与职位由身份提供商或管理员管理。已验证：{profile.emailVerified ? "是" : "否"}</p><div className="settings-card-actions"><Button variant="primary" onClick={onSave}>保存个人资料</Button><Button>撤销</Button></div></section>
    <section className="settings-card"><h2>显示与区域</h2><div className="settings-form-grid three"><label>语言<select value={profile.locale} onChange={(event) => onChange({ ...profile, locale: event.target.value as ProfileSettings["locale"] })}><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><label>数字格式<select value={profile.numberFormat} onChange={(event) => onChange({ ...profile, numberFormat: event.target.value as ProfileSettings["numberFormat"] })}><option value="comma_dot">1,234.56</option><option value="space_comma">1 234,56</option></select></label><label>时区<select value={profile.timezone} onChange={(event) => onChange({ ...profile, timezone: event.target.value })}><option>Asia/Shanghai</option><option>UTC</option></select></label><label>默认页面<select value={profile.defaultRoute} onChange={(event) => onChange({ ...profile, defaultRoute: event.target.value as ProfileSettings["defaultRoute"] })}><option value="/command">Command Center</option><option value="/research">Research</option><option value="/portfolio">Portfolio</option><option value="/markets">Markets</option></select></label><label>主题<select value={profile.theme} onChange={(event) => onChange({ ...profile, theme: event.target.value as ProfileSettings["theme"] })}><option value="dark">深色</option><option value="light">浅色</option><option value="system">系统</option></select></label><label>密度<select value={profile.density} onChange={(event) => onChange({ ...profile, density: event.target.value as ProfileSettings["density"] })}><option value="compact">紧凑</option><option value="comfortable">舒适</option></select></label></div><div className="settings-accessibility"><MiniToggle checked={profile.highContrast} onChange={(value) => onChange({ ...profile, highContrast: value })} label="高对比度" /><MiniToggle checked={profile.reducedMotion} onChange={(value) => onChange({ ...profile, reducedMotion: value })} label="减少动画" /></div></section>
  </div>;
}

function NotificationsPanel({ value, onChange, onSave, runtimePermission }: { value: NotificationPreferences; onChange: (next: NotificationPreferences) => void; onSave: () => void; runtimePermission: BrowserPermissionState }) {
  function updateRule(index: number, channel: NotificationChannel, checked: boolean) { onChange({ ...value, rules: value.rules.map((rule, ruleIndex) => ruleIndex === index ? { ...rule, [channel]: checked } : rule) }); }
  return <div className="settings-column"><section className="settings-card"><div className="settings-card-title"><h2>通知矩阵</h2><span>浏览器权限：<b className={runtimePermission === "granted" ? "good-text" : "warn-text"}>{runtimePermission}</b></span></div><InlineAlert tone={runtimePermission === "granted" ? "success" : "warning"} title={notificationFallback(runtimePermission) === "browser" ? "浏览器通知可用" : "已降级为站内通知"}>拒绝或不支持浏览器通知不会影响站内风险状态，也不会反复弹窗。</InlineAlert><div className="notification-matrix" role="table" aria-label="通知偏好矩阵"><div className="notification-row head" role="row"><span role="columnheader">通知类型</span><span role="columnheader">严重性</span>{Object.values(channelLabels).map((label) => <span role="columnheader" key={label}>{label}</span>)}</div>{value.rules.map((rule, index) => <div className="notification-row" role="row" key={rule.key}><strong role="cell">{ruleLabels[rule.key] ?? rule.key}</strong><b role="cell" className={`severity-${rule.severity}`}>{rule.severity}</b>{(Object.keys(channelLabels) as NotificationChannel[]).map((channel) => <span role="cell" key={channel}><MiniToggle checked={rule[channel]} disabled={channel === "browser" && runtimePermission !== "granted"} onChange={(checked) => updateRule(index, channel, checked)} label={rule[channel] ? "On" : "Off"} /></span>)}</div>)}</div><div className="settings-quiet"><label>静默时段<input type="time" value={value.quietHoursStart} onChange={(event) => onChange({ ...value, quietHoursStart: event.target.value })} /> – <input type="time" value={value.quietHoursEnd} onChange={(event) => onChange({ ...value, quietHoursEnd: event.target.value })} /></label><MiniToggle checked={value.criticalBypass} onChange={(checked) => onChange({ ...value, criticalBypass: checked })} label="Critical 绕过静默" /><label>摘要频率<select value={value.digestFrequency} onChange={(event) => onChange({ ...value, digestFrequency: event.target.value as NotificationPreferences["digestFrequency"] })}><option value="off">关闭</option><option value="daily">Daily 08:00</option><option value="weekly">Weekly</option></select></label><Button variant="primary" onClick={onSave}>保存通知偏好</Button></div></section></div>;
}

function SecurityPanel({ data, sessions, devices, online, viewportWidth, onSessionRevoked, onDeviceRevoked }: { data: SettingsBundle; sessions: SettingsBundle["sessions"]; devices: SettingsBundle["devices"]; online: boolean; viewportWidth: number; onSessionRevoked: (id: string) => void; onDeviceRevoked: (id: string) => void }) {
  return <div className="settings-security-grid"><section className="settings-card security-score"><div><h2>安全中心</h2><p>Security posture · <b>{data.security.posture}</b></p></div><strong>♢ {data.security.score}</strong><dl><dt>MFA</dt><dd>{data.security.mfaEnabled ? "已启用" : "未启用"}</dd><dt>主要方式</dt><dd>{data.security.factors[0]?.method}</dd><dt>恢复代码</dt><dd>{data.security.recoveryCodesRemaining} remaining</dd><dt>上次验证</dt><dd>{formatDate(data.security.lastVerifiedAt)}</dd></dl><div className="settings-card-actions"><Button>添加 Passkey</Button><Button>管理 MFA</Button></div><p className="warn-text">△ 安全变更需要近期登录验证。</p></section>
    <section className="settings-card span-two"><h2>活动会话 {sessions.length}</h2><div className="settings-list-table"><div className="settings-list-row head"><span>设备与浏览器</span><span>位置</span><span>最后活动</span><span>会话 ID / IP</span><span>状态</span></div>{sessions.map((session) => <div className="settings-list-row" key={session.sessionId}><strong>{session.client}<small>{session.platform}</small></strong><span>{session.location}</span><time dateTime={session.lastActiveAt}>{formatDate(session.lastActiveAt)}</time><code>{session.sessionId}<small>{session.ipMasked}</small></code>{session.current ? <b className="good-text">● 当前</b> : <DangerConfirmDialog trigger={<Button className="settings-high-risk" variant="danger" disabled={!canRevokeSession(session, { online, viewportWidth })}>撤销会话</Button>} title="撤销活动会话" summary={`即将撤销 ${session.client} 的会话。`} impact="该设备会立即失去访问权限，未提交的本地操作不会自动恢复。" confirmPhrase={`REVOKE ${session.sessionId}`} confirmLabel="确认撤销会话" mfaRequired correlationId={data.security.correlationId} onConfirm={async () => onSessionRevoked(session.sessionId)} />}</div>)}</div></section>
    <section className="settings-card span-two"><h2>可信设备 {devices.length}</h2><div className="settings-list-table devices">{devices.map((device) => <div className="settings-list-row" key={device.deviceId}><strong>{device.label}</strong><span>{device.verificationMethod}</span><time dateTime={device.trustedUntil}>信任至 {formatDate(device.trustedUntil)}</time>{device.current ? <b className="good-text">● 当前</b> : <DangerConfirmDialog trigger={<Button className="settings-high-risk" variant="danger" disabled={!canRevokeDevice({ online, viewportWidth, factorCount: data.security.factors.length })}>撤销信任</Button>} title="撤销可信设备" summary={`即将撤销 ${device.label} 的信任。`} impact="该设备下一次访问时必须重新完成身份验证；最后有效 MFA 因素不会被撤销。" confirmPhrase={`REVOKE ${device.deviceId}`} confirmLabel="确认撤销信任" mfaRequired correlationId={data.security.correlationId} onConfirm={async () => onDeviceRevoked(device.deviceId)} />}</div>)}</div></section>
    <section className="settings-card span-two"><h2>安全操作</h2><div className="security-actions"><Button>下载恢复代码</Button><Button>重新验证身份</Button><Button>查看登录活动</Button><span className="q-mono">Correlation ID: {data.security.correlationId}</span></div></section></div>;
}

function BrowserPanel({ data, runtime, onRequestPermission, notice }: { data: SettingsBundle; runtime?: BrowserRuntimeCapabilities; onRequestPermission: () => void; notice: (message: string) => void }) {
  const caps = runtime ? [["WebSocket", runtime.webSocket], ["SSE", runtime.serverSentEvents], ["Notifications", runtime.notifications === "granted"], ["Clipboard", runtime.clipboard], ["Download", runtime.downloads], ["Service worker", runtime.serviceWorker], ["IndexedDB", runtime.indexedDb], ["Passkey", runtime.passkey]] as const : [];
  return <div className="browser-settings-grid"><section className="settings-card"><h2>♧ 浏览器通知 <b className="warn-text">{runtime?.notifications ?? "detecting"}</b></h2><p>允许通知后，我们只会推送你有权查看的高优先级事件。</p><dl><dt>Permission source</dt><dd>Browser API</dd><dt>Availability</dt><dd>{runtime?.notifications === "unsupported" ? "Unsupported" : "Supported"}</dd><dt>Fallback</dt><dd>页面内通知已启用</dd></dl><div className="settings-card-actions"><Button variant="primary" onClick={onRequestPermission}>请求浏览器通知权限</Button><Button>打开浏览器网站设置</Button></div><p className="settings-note">只会在你点击后调用浏览器权限；拒绝后不会重复弹窗。</p></section>
    <section className="settings-card downloads-card"><h2>⌄ 最近下载记录</h2><div className="downloads-list" role="region" aria-label="最近下载记录" tabIndex={0}>{data.downloads.map((record) => { const availability = downloadAvailability(record, new Date().toISOString()); return <div key={record.downloadId}><strong>{record.objectLabel}</strong><span>{record.format}</span><time dateTime={record.requestedAt}>{formatDate(record.requestedAt)}</time><b className={availability.available ? "good-text" : "muted-text"}>{record.status}</b><Button disabled={!availability.available} onClick={() => notice(availability.reason)}>下载</Button></div>; })}</div><InlineAlert title="下载安全说明">文件仅通过 BFF 短时签名 URL 提供；链接过期、越权或已撤销时必须重新生成，下载会写入审计。</InlineAlert></section>
    <section className="settings-card storage-card"><h2>▱ 会话与站点存储</h2><ul><li>Auth session <b>Protected · short-lived</b></li><li>Cookies <b>Secure · HttpOnly · SameSite</b></li><li>Local storage <b>仅用户偏好</b></li><li>IndexedDB <b>{runtime?.indexedDb ? "可用" : "不可用"}</b></li><li>Secrets/tokens <b>JavaScript 不可读取</b></li></ul><p>领域秘密不会存储在浏览器；离线状态只读。</p></section>
    <section className="settings-card deep-link-card"><h2>⌁ 授权深链</h2><code>{data.browserPolicy.deepLinkScheme}</code><ul><li>✓ Resource reference only</li><li>✓ no account data</li><li>✓ authorization rechecked</li><li>✓ route does not grant access</li></ul><div className="settings-card-actions"><Button onClick={() => notice("深链引用已复制；其中不含 token、账户数据或签名。")}>复制深链</Button><Button>在新标签页验证</Button></div></section>
    <section className="settings-card responsive-card"><h2>响应式与操作限制</h2><div className="responsive-preview"><div>Desktop 1440px<strong>完整工作区，受 RBAC 控制</strong></div><div>Mobile 390px<strong>只读状态卡片</strong></div></div><InlineAlert tone="warning" title="小屏只读规则">小于 768px 时隐藏审批、撤销会话、撤销设备、下单和其他高风险主操作；请使用桌面浏览器完成。</InlineAlert></section>
    <aside className="settings-card browser-status"><h2>Browser 状态</h2><p className="good-text">♢ Ready</p><dl><dt>kind</dt><dd>{data.browserPolicy.kind}</dd><dt>authFlow</dt><dd>{data.browserPolicy.authFlow}</dd><dt>notifications</dt><dd>{data.browserPolicy.notifications}</dd><dt>localFileImport</dt><dd>{String(data.browserPolicy.localFileImport)}</dd><dt>downloadsViaBff</dt><dd>{String(data.browserPolicy.downloadsViaBff)}</dd></dl><h3>兼容性检测</h3><p>{runtime?.browserLabel ?? "检测中"} · {runtime?.operatingSystem}</p>{caps.map(([name, supported]) => <p key={name}>{supported ? "✓" : "△"} {name}: <b className={supported ? "good-text" : "warn-text"}>{supported ? "Supported" : "Limited"}</b></p>)}<h3>网页端限制</h3><ul><li>无原生多窗口恢复</li><li>无系统文件关联</li><li>无离线领域操作</li><li>下载仅通过 BFF 签名 URL</li></ul></aside></div>;
}

export function SettingsWorkspace({ section, initialData, contractMode = "mocked", pageState = "default", platformKind = "web" }: SettingsWorkspaceProps) {
  const [profile, setProfile] = useState(initialData.profile); const [notifications, setNotifications] = useState(initialData.notifications); const [sessions, setSessions] = useState(initialData.sessions); const [devices, setDevices] = useState(initialData.devices);
  const [online, setOnline] = useState(true); const [viewportWidth, setViewportWidth] = useState(1440); const [runtime, setRuntime] = useState<BrowserRuntimeCapabilities>(); const [notice, setNotice] = useState("");
  useEffect(() => { const update = () => { setOnline(navigator.onLine); setViewportWidth(window.innerWidth); setRuntime(detectBrowserRuntime(window)); }; update(); window.addEventListener("online", update); window.addEventListener("offline", update); window.addEventListener("resize", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); window.removeEventListener("resize", update); }; }, []);
  const data = useMemo(() => ({ ...initialData, profile, notifications, sessions, devices }), [devices, initialData, notifications, profile, sessions]);
  async function requestPermission() { if (!("Notification" in window)) { setNotice("当前浏览器不支持通知，已保持站内通知。 "); return; } const permission = await Notification.requestPermission(); setRuntime(detectBrowserRuntime(window)); setNotice(permission === "granted" ? "浏览器通知已授权。" : "浏览器通知未授权，已降级为站内通知且不会重复请求。"); }
  return <ThemeProvider theme="dark"><div className="settings-shell" data-ui104-section={section}>
    <header className="settings-topbar"><a href="/command" className="settings-brand"><span>◢</span> SUMALPHA</a><button>▣ Primary workspace⌄</button><button>Paper Account 01⌄</button><b>PAPER</b><span className="settings-spacer" /><label>⌕ <input aria-label="全局搜索" placeholder="搜索 ⌘K" /></label><button aria-label="通知">♧ 3</button><button aria-label="帮助">?</button><button aria-label="个人菜单">AN⌄</button></header>
    <aside className="settings-main-nav" aria-label="主导航"><a href="/command">⌂ Command</a><a href="/research">◉ Research</a><a href="/strategies">↗ Strategy</a><a href="/portfolio">◔ Portfolio</a><a href="/markets">▥ Markets</a><a href="/trade">⇄ Trade</a><a href="/approvals">✓ Approvals <b>3</b></a><a href="/orders">▣ Orders <b>2</b></a><a href="/audit">▥ Audit</a><a href="/operations">≋ Operations</a><a href="/admin/members">⚙ Admin</a></aside>
    <main className="settings-main" data-smoke={`route-/settings/${section}`}><SettingsHeader section={section} />{contractMode === "mocked" ? <div className="contract-mocked-banner" role="status">C17 Local Mock · 页面数据来自 OpenAPI 1.2.0 同源 fixture；本地参考 provider 已实现，staging BFF 签署待完成。</div> : null}{(!online || pageState === "offline") ? <InlineAlert tone="danger" title="当前离线">设置保持只读；恢复连接后不会自动重放保存或撤销操作。</InlineAlert> : null}{pageState === "stale" ? <InlineAlert tone="warning" title="数据可能已过期">展示上次同步的设置快照；写操作已暂停，刷新成功后再继续。</InlineAlert> : null}<div className="settings-layout"><SettingsIdentity profile={profile} active={section} platformKind={platformKind} /><div className="settings-content">
      {pageState !== "default" && pageState !== "stale" && pageState !== "offline" ? <SettingsState state={pageState} /> : null}
      {section === "browser" && !shouldExposeBrowserSettings(platformKind) ? <InlineAlert tone="warning" title="仅 Web 提供">浏览器能力设置不会在 Desktop 导航或内容区展示；请使用 Web 终端。</InlineAlert> : null}
      <fieldset className="settings-panels" disabled={!online || pageState === "stale" || pageState === "offline"}>
      {(pageState === "default" || pageState === "stale" || pageState === "offline") && section === "profile" ? <ProfilePanel profile={profile} onChange={setProfile} onSave={() => setNotice("个人资料已保存；角色、权限与风险规则未发生变化。 ")}/> : null}
      {(pageState === "default" || pageState === "stale" || pageState === "offline") && section === "notifications" ? <NotificationsPanel value={notifications} onChange={setNotifications} runtimePermission={runtime?.notifications ?? notifications.browserPermission} onSave={() => setNotice("通知偏好已保存；不可见事件仍不会通过任一渠道推送。")}/> : null}
      {(pageState === "default" || pageState === "stale" || pageState === "offline") && section === "security" ? <SecurityPanel data={data} sessions={sessions} devices={devices} online={online && pageState === "default"} viewportWidth={viewportWidth} onSessionRevoked={(id) => { setSessions((items) => items.filter((item) => item.sessionId !== id)); setNotice("会话撤销已受理；最终状态将由会话撤销事件确认。"); }} onDeviceRevoked={(id) => { setDevices((items) => items.filter((item) => item.deviceId !== id)); setNotice("设备信任撤销已受理。"); }} /> : null}
      {(pageState === "default" || pageState === "stale" || pageState === "offline") && section === "browser" && shouldExposeBrowserSettings(platformKind) ? <BrowserPanel data={data} runtime={runtime} onRequestPermission={() => void requestPermission()} notice={setNotice} /> : null}
      </fieldset>
    </div></div></main><footer className="settings-statusbar"><span>● Connection: {online ? "Live" : "Offline"}</span><span>● Realtime: {online ? "Connected" : "Disconnected"}</span><span>● Settings synced</span><span>Session protected</span><span>Last sync 11:34:42</span></footer>{notice ? <div className="toast" role="status"><span>{notice}</span><button onClick={() => setNotice("")} aria-label="关闭通知">×</button></div> : null}
  </div></ThemeProvider>;
}
