import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {validateEvidence,selectors,targetAssertions,mutantNames,targetSourcePaths} from './bff-fe-001-development.mjs';
import {inventory,root,digest,nodesFromPlans,planInput} from './provider-a1-receipts.mjs';
import {executionSources} from './bff-fe-001-execution.mjs';
function fixture(){
 const inputs=inventory(selectors),bytes=new Map(),put=(path,value)=>{const raw=Buffer.from(typeof value==='string'?value:JSON.stringify(value));bytes.set(path,raw);return digest(raw);};
 const n=nodesFromPlans().get('FE:BFF-FE-001');const dependencies=new Map(n.dependencies.map(id=>[id,{status:'READY',input_digest:'sha256:fixture'}]));
 const semanticLogs=[0,1,2].map(i=>({path:'log-'+i}));semanticLogs.forEach(l=>put(l.path,'test result: ok. 12 passed'));
 const hashes=Object.fromEntries(Object.entries(executionSources).map(([name,path])=>[name,inputs.find(i=>i.path===path).sha256.slice(7)]));
 const semantics={status:'PASS',sourceHashes:hashes,results:[['cargo',['test','--locked','--offline','-p','bff-gateway','--lib']],['cargo',['test','--locked','--offline','-p','bff-gateway','--test','auth_settings_provider']],['pnpm',['--filter','@sumalpha/terminal','exec','vitest','run','tests/auth-bff.test.ts','tests/ui104-settings.test.ts']]].map(([command,args],i)=>({command,args,exitCode:0,outputSha256:digest(bytes.get('log-'+i)).slice(7)}))};
 const mutationLogs=mutantNames.map(name=>({name,path:'mutant-'+name}));mutationLogs.forEach(l=>put(l.path,'assertion ... FAILED'));
 const mutations={sourceSha256:inputs.find(i=>i.path==='services/bff-gateway/src/lib.rs').sha256.slice(7),livePolicySha256:hashes.livePolicy,records:mutantNames.map(name=>({name,rejected:true,exitCode:101,expectedTest:'assertion',outputSha256:digest(bytes.get('mutant-'+name)).slice(7)}))};
 const live={schema:'quantos-bff-a2-live-regression/v1',status:'PASS',failure:null,scope:'configured existing Supabase Auth/PostgreSQL; local live BFF',assertions:targetAssertions,correlations:['a','b','c','d','e'],cleanupVerified:true,sourceHashes:Object.fromEntries(targetSourcePaths.map(path=>[path,inputs.find(i=>i.path===path).sha256.slice(7)])),records:['getSession','getContext','reauth','mfaChallenge','logout','submitAccessRequest','getProfile','saveProfile','getNotificationPrefs','saveNotificationPrefs','getSecuritySettings','listSessions','revokeSession','subscribeSessionRevocations','listDevices','revokeDevice','setupMfa','revokeMfaFactor','listDownloads','getPlatformCapabilities'].map(operationId=>({operationId,status:200,issues:[]}))};
 const contents={semantics,mutations,live,traces:live.correlations.map(c=>JSON.stringify({correlation_id:c,status:'succeeded'})).join('\n'),'contract-negative':'# fail 0','stage-negative':'# fail 0'};
 const m={schema:'quantos-bff-a2-development-manifest/v1',nodeId:n.id,stage:'DEVELOPMENT',status:'PASS',formalAccepted:false,residuals:[],observedSourceCommit:'a'.repeat(40),environment:{node:'24',rust:'1.91',target:'configured-supabase'},inputs,planInput:planInput(n),dependencies:[...dependencies].map(([nodeId,g])=>({nodeId,inputDigest:g.input_digest})),semanticLogs,mutationLogs,checks:Object.entries(contents).map(([id,value])=>({id,path:id,sha256:put(id,value),status:'PASS',exitCode:0}))};
 return {m,bytes,options:{currentInputs:inputs,currentPlan:planInput(n),dependencies,read:p=>bytes.get(p),validateDependency:()=>{}},change(id,f){const raw=JSON.parse(bytes.get(id));f(raw);m.checks.find(c=>c.id===id).sha256=put(id,raw);}};
}
test('complete current evidence passes with all dependencies checked',()=>{const f=fixture(),visited=[];f.options.validateDependency=id=>visited.push(id);assert.equal(validateEvidence(f.m,f.options).status,'READY');assert.equal(visited.length,3);});
for(const [name,mutate]of [
 ['own failure',f=>f.m.status='FAIL'],['residual defect',f=>f.m.residuals.push('H-01')],['stale code',f=>f.options.currentInputs=structuredClone(f.m.inputs).map((i,j)=>j?i:{...i,sha256:'changed'})],['upstream not READY',f=>f.options.dependencies.values().next().value.status='NOT_ASSESSED'],['upstream digest changed',f=>f.options.dependencies.values().next().value.input_digest='changed'],['recursive upstream failure',f=>f.options.validateDependency=()=>{throw Error('nested source stale');}],['evidence tampered',f=>f.bytes.set('live',Buffer.from('{}'))],['target assertion missing',f=>f.change('live',r=>r.assertions=r.assertions.slice(1))],['cleanup unverified',f=>f.change('live',r=>r.cleanupVerified=false)],['live policy mutant survives',f=>f.change('mutations',r=>r.records[3].rejected=false)],['live semantic test omitted',f=>f.change('semantics',r=>r.results.shift())],['target source stale',f=>f.change('live',r=>r.sourceHashes[Object.keys(r.sourceHashes)[0]]='old')],['audit trace absent',f=>{const raw=Buffer.from('{}');f.bytes.set('traces',raw);f.m.checks.find(c=>c.id==='traces').sha256=digest(raw);}]
])test(name+' is rejected',()=>{const f=fixture();mutate(f);assert.throws(()=>validateEvidence(f.m,f.options));});
