const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {retireDatabaseFixtures,validateDatabaseCleanup}=require('./lib/f06-database-fixtures.cjs');
const run='11111111-1111-4111-8111-111111111111';
const fixture=i=>{const tenantId='22222222-2222-4222-8222-'+String(i).padStart(12,'0'),userId='33333333-3333-4333-8333-'+String(i).padStart(12,'0');return {run,tenantId,userId,slug:'f06-'+tenantId};};
function mock({wrongOwner=false,active=false,reset=false}={}){
 const queries=[];let closed=false;
 class Client extends EventEmitter{async connect(){}async end(){closed=true;}async query(sql,args){queries.push({sql,args});const f=fixture(Number(args[0].slice(-12)));if(sql.startsWith('select id,slug'))return {rows:[{id:args[0],slug:wrongOwner?'other':'f06-'+args[0]}]};if(sql.startsWith('select id,email'))return {rows:[{id:args[0],email:'f06-'+args[0]+'@example.com'}]};if(reset&&sql.startsWith('update'))this.emit('error',Object.assign(Error('private'),{code:'ECONNRESET'}));if(sql.startsWith('select (select count'))return {rows:[{active_actors:active?1:0,active_accounts:0,active_execution_sessions:0,active_bff_sessions:0}]};return {rows:[]};}}
 return {queries,options:{createClient:()=>new Client(),pause:async()=>{}},isClosed:()=>closed};
}
test('all eight registered fixtures retire by exact identity without deleting facts',async()=>{const m=mock();const r=await retireDatabaseFixtures(Array.from({length:8},(_,i)=>fixture(i+1)),run,m.options);validateDatabaseCleanup(r);assert(m.isClosed());assert(!m.queries.some(q=>/delete|drop|truncate/i.test(q.sql)));assert(m.queries.filter(q=>q.sql.startsWith('update')).every(q=>q.args.length===1));});
test('wrong tenant ownership stops before any mutation',async()=>{const m=mock({wrongOwner:true});const r=await retireDatabaseFixtures([fixture(1)],run,m.options);assert.equal(r.status,'FAIL');assert(!m.queries.some(q=>q.sql.startsWith('update')));assert(m.isClosed());});
test('remaining active actor rejects cleanup success',async()=>{const m=mock({active:true});assert.equal((await retireDatabaseFixtures([fixture(1)],run,m.options)).status,'FAIL');assert(m.isClosed());});
test('post-SQL disconnect is recorded and no mutation replays',async()=>{const m=mock({reset:true});const r=await retireDatabaseFixtures([fixture(1)],run,m.options);assert.equal(r.status,'FAIL');assert.equal(r.failure.code,'ECONNRESET');assert.equal(m.queries.filter(q=>q.sql.startsWith('update')).length,1);assert(m.isClosed());});
test('duplicate or wrong-run fixture inventory never opens a connection',async()=>{for(const records of [[fixture(1),fixture(1)],[{...fixture(1),run:'other'}]]){const m=mock();await assert.rejects(retireDatabaseFixtures(records,run,m.options));assert.equal(m.queries.length,0);}});
test('admission rejects partial inventory, unclosed connection, active sessions and missing cleanup',async()=>{const m=mock();const r=await retireDatabaseFixtures(Array.from({length:8},(_,i)=>fixture(i+1)),run,m.options);for(const mutate of [x=>x.fixtures.pop(),x=>x.bootstrapConnection.connectionClosed=false,x=>x.fixtures[0].active_execution_sessions=1,x=>x.status='FAIL',x=>x.fixtures[0].tenantPresent=false]){const bad=structuredClone(r);mutate(bad);assert.throws(()=>validateDatabaseCleanup(bad));}assert.throws(()=>validateDatabaseCleanup(null));});
