const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {retireF09Fixtures,validateF09Cleanup}=require('./lib/f09-fixtures.cjs');
const run='11111111-1111-4111-8111-111111111111';
const fixtures=['fault','db-disconnect','live'].map((kind,i)=>{const tenantId='22222222-2222-4222-8222-'+String(i+1).padStart(12,'0'),actorId='33333333-3333-4333-8333-'+String(i+1).padStart(12,'0');return {run,tenantId,actorId,scope:'f09-'+kind+'-'+run+'-'+tenantId};});
function mock({wrongOwner=false,reset=false,active=false,changed=false}={}){const queries=[];let closed=false;class Client extends EventEmitter{async connect(){}async end(){closed=true;}async query(sql,args){queries.push({sql,args});const f=fixtures.find(f=>f.tenantId===args[0]||f.actorId===args[0]);if(sql.startsWith('select id,slug'))return {rows:[{slug:wrongOwner?'unowned':f.scope}]};if(sql.startsWith('select id,tenant'))return {rows:[{tenant_id:f.tenantId,service_name:'f09-test-'+f.actorId}]};if(sql.startsWith('select count'))return {rows:[{n:1}]};if(sql.startsWith('update')&&reset)this.emit('error',Object.assign(Error('reset'),{code:'ECONNRESET'}));if(sql.startsWith('select (select'))return {rows:[{active_actors:active?1:0,events:changed?0:1}]};return {rows:[]};}}return {queries,closed:()=>closed,options:{createClient:()=>new Client(),pause:async()=>{}}};}
test('three exact owned actors retire while immutable event facts remain',async()=>{const m=mock();const r=await retireF09Fixtures(fixtures,run,m.options);validateF09Cleanup(r);assert(m.closed());assert(!m.queries.some(q=>/delete|truncate|drop/i.test(q.sql)));assert(m.queries.filter(q=>q.sql.startsWith('update')).every(q=>q.args.length===3));});
test('ownership mismatch refuses mutation',async()=>{const m=mock({wrongOwner:true});assert.equal((await retireF09Fixtures(fixtures,run,m.options)).status,'FAIL');assert(!m.queries.some(q=>q.sql.startsWith('update')));assert(m.closed());});
test('post-SQL reset is FAIL with no replay',async()=>{const m=mock({reset:true});const r=await retireF09Fixtures(fixtures,run,m.options);assert.equal(r.status,'FAIL');assert.equal(r.failure.code,'ECONNRESET');assert.equal(m.queries.filter(q=>q.sql.startsWith('update')).length,1);assert(m.closed());});
test('active actors and changed event facts fail retirement',async()=>{for(const options of [{active:true},{changed:true}]){const m=mock(options);assert.equal((await retireF09Fixtures(fixtures,run,m.options)).status,'FAIL');assert(m.closed());}});
test('wrong run and duplicate actors never connect',async()=>{for(const fs of [[fixtures[0],fixtures[0]],[{...fixtures[0],run:'other'}]]){const m=mock();await assert.rejects(retireF09Fixtures(fs,run,m.options));assert.equal(m.queries.length,0);}});
test('empty fixture inventory cannot admit successful F09',async()=>{const r=await retireF09Fixtures([],run);assert.equal(r.status,'NOT_NEEDED_NO_REGISTERED_FIXTURE');assert.throws(()=>validateF09Cleanup(r));});
test('partial, open, changed and active cleanup receipts fail admission',async()=>{const m=mock();const r=await retireF09Fixtures(fixtures,run,m.options);for(const mutate of [x=>x.fixtures.pop(),x=>x.bootstrapConnection.connectionClosed=false,x=>x.fixtures[0].eventsAfter=0,x=>x.fixtures[0].activeActors=1,x=>x.fixtures[0].actorPresent=false]){const bad=structuredClone(r);mutate(bad);assert.throws(()=>validateF09Cleanup(bad));}});
