const test=require('node:test'),assert=require('node:assert/strict');
const {connectBeforeStatements,validateBootstrap}=require('./lib/postgres-bootstrap.cjs');
function fixture(errors){const record={},clients=[];const factory=()=>{const i=clients.length;const c={queries:0,closed:false,async connect(){if(errors[i])throw errors[i];},async end(){c.closed=true;},async query(){c.queries++;}};clients.push(c);return c;};return {record,clients,factory};}
const closed=()=>Error('Connection terminated unexpectedly');
test('two closed initial connections are retained, closed, then the third succeeds before any statement',async()=>{const f=fixture([closed(),closed()]);let records=0;await connectBeforeStatements(f.factory,{record:f.record,pause:async()=>{},onAttempt(){records++;}});validateBootstrap(f.record);assert.equal(records,3);assert.equal(f.clients.length,3);assert(f.clients.slice(0,2).every(c=>c.closed));assert(f.clients.every(c=>c.queries===0));});
test('persistent closure fails after three and retains every failure',async()=>{const f=fixture([closed(),closed(),closed()]);await assert.rejects(connectBeforeStatements(f.factory,{record:f.record,pause:async()=>{}}));assert.equal(f.clients.length,3);assert.equal(f.record.status,'FAIL');assert(f.clients.every(c=>c.closed));assert.throws(()=>validateBootstrap(f.record));});
for(const [name,error]of [['auth',Object.assign(Error('bad password'),{code:'28P01'})],['permission',Object.assign(closed(),{code:'42501'})],['TLS',Object.assign(Error('certificate invalid'),{code:'CERT_HAS_EXPIRED'})],['cancel',Object.assign(closed(),{name:'AbortError'})],['unknown',Error('private database password must not appear')]])test(name+' bootstrap failure never retries',async()=>{const f=fixture([error]);await assert.rejects(connectBeforeStatements(f.factory,{record:f.record,pause:async()=>{}}));assert.equal(f.clients.length,1);assert(f.clients[0].closed);assert(!JSON.stringify(f.record).includes(error.message));});
test('initial transport timeout retries but a later query error never reconnects',async()=>{const f=fixture([Object.assign(Error('private details'),{code:'ETIMEDOUT'})]);const client=await connectBeforeStatements(f.factory,{record:f.record,pause:async()=>{}});client.query=async()=>{throw closed();};await assert.rejects(client.query());assert.equal(f.clients.length,2);validateBootstrap(f.record);});
test('failure to close an initial connection prevents retry',async()=>{const f=fixture([closed()]);const factory=()=>{const c=f.factory();c.end=async()=>{throw Error('close failed');};return c;};await assert.rejects(connectBeforeStatements(factory,{record:f.record,pause:async()=>{}}));assert.equal(f.clients.length,1);assert.equal(f.record.attempts[0].cleanupFailed,true);});
test('budget cannot exceed three',async()=>{for(const n of [0,4,1.5,Infinity])await assert.rejects(connectBeforeStatements(()=>{throw Error('must not create');},{record:{},maxAttempts:n}));});
test('acceptance rejects missing, unfinished, reordered, semantic or unclosed attempts',async()=>{const f=fixture([closed()]);await connectBeforeStatements(f.factory,{record:f.record,pause:async()=>{}});for(const change of [r=>r.status='RUNNING',r=>r.attempts=[],r=>r.attempts[0].attempt=2,r=>r.attempts[0].errorKind='POSTGRES_42501',r=>r.attempts[0].connectionClosed=false,r=>r.maxAttempts=4,r=>r.attempts[1].elapsedMs=-1]){const r=structuredClone(f.record);change(r);assert.throws(()=>validateBootstrap(r));}});

test('evidence-save failure closes the connected client and never reconnects',async()=>{const f=fixture([]);await assert.rejects(connectBeforeStatements(f.factory,{record:f.record,onAttempt(){throw Error('evidence unavailable');}}));assert.equal(f.clients.length,1);assert(f.clients[0].closed);});
