const test=require('node:test'),assert=require('node:assert/strict'),ready=require('./lib/service-readiness.cjs');
function fixture(){let elapsed=0;const service={child:{exitCode:null,signalCode:null},base:'http://owned-fixture',diagnostic:()=> 'sanitized startup'};return{service,options:{now:()=>elapsed,pause:async ms=>{elapsed+=ms;}},elapsed:()=>elapsed,advance:ms=>{elapsed+=ms;}};}
test('initialization after the old 20s loop can pass only with an exact readiness response',async()=>{const f=fixture();const r=await ready(f.service,'/healthz',204,{...f.options,probe:async()=>({status:f.elapsed()>20000?204:503})});assert(r.elapsedMs>20000&&r.elapsedMs<=60000);assert.equal(r.performanceAccepted,false);assert.deepEqual(f.service.readiness,r);});
test('a never-ready service exhausts one bounded wall-clock budget',async()=>{const f=fixture();await assert.rejects(ready(f.service,'/healthz',204,{...f.options,probe:async()=>({status:503})}),/60000ms/);assert.equal(f.elapsed(),60000);assert.equal(f.service.readiness,undefined);});
test('response after deadline cannot grant readiness',async()=>{const f=fixture();await assert.rejects(ready(f.service,'/healthz',204,{...f.options,probe:async()=>{f.advance(60001);return{status:204};}}),/did not become ready/);});
test('exited or killed services fail without waiting or probing',async()=>{for(const key of ['exitCode','signalCode']){const f=fixture();f.service.child[key]=key==='exitCode'?1:'SIGTERM';let calls=0;await assert.rejects(ready(f.service,'/healthz',204,{...f.options,probe:async()=>{calls++;return{status:204};}}));assert.equal(calls,0);assert.equal(f.elapsed(),0);}});
test('connection failures and wrong successful HTTP status cannot pass',async()=>{for(const probe of [async()=>{throw Error('connection refused');},async()=>({status:200})]){const f=fixture();await assert.rejects(ready(f.service,'/healthz',204,{...f.options,probe}));assert.equal(f.service.readiness,undefined);}});
test('invalid or unbounded startup budgets reject',async()=>{for(const budgetMs of [0,14999,60001,Infinity,1.5]){const f=fixture();await assert.rejects(ready(f.service,'/healthz',204,{...f.options,budgetMs}));}});

test('process exit during a successful probe cannot grant readiness',async()=>{const f=fixture();await assert.rejects(ready(f.service,'/healthz',204,{...f.options,probe:async()=>{f.service.child.exitCode=1;return{status:204};}}));assert.equal(f.service.readiness,undefined);});
