[package]
name = "execution-gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
quantos-auth = { version = "0.1.0", path = "../../crates/quantos-auth" }
quantos-core = { version = "0.1.0", path = "../../crates/quantos-core" }
quantos-execution = { version = "0.1.0", path = "../../crates/quantos-execution" }
quantos-observability = { version = "0.1.0", path = "../../crates/quantos-observability" }
rust_decimal.workspace = true
uuid.workspace = true
